# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bldgquery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
                ('plus4', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bldgquery.Building'),
        ),
    ]
