# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bldgquery', '0004_auto_20170412_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BBNum', models.IntegerField()),
                ('centerLat', models.FloatField()),
                ('centerLon', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
        migrations.AddField(
            model_name='building',
            name='BIN',
            field=models.IntegerField(default=9999999999),
        ),
        migrations.AddField(
            model_name='building',
            name='numFloors',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='building',
            name='roofHeight',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='building',
            name='streetName',
            field=models.CharField(default='Boogie-Boogie Ave', max_length=50),
        ),
        migrations.AddField(
            model_name='building',
            name='streetNumber',
            field=models.CharField(default=1122, max_length=10),
        ),
        migrations.AlterField(
            model_name='building',
            name='dateBuilt',
            field=models.IntegerField(default=1800),
        ),
        migrations.AddField(
            model_name='building',
            name='block',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='bldgquery.Block'),
        ),
    ]
