# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldgquery', '0005_auto_20170413_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='bCenterLat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='building',
            name='bCenterLon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='building',
            name='BIN',
            field=models.IntegerField(default=9999999),
        ),
        migrations.AlterField(
            model_name='building',
            name='roofHeight',
            field=models.FloatField(default=15),
        ),
    ]
