# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldgquery', '0006_auto_20170413_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='bCenterLat',
            new_name='centerLat',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='bCenterLon',
            new_name='centerLon',
        ),
        migrations.RemoveField(
            model_name='building',
            name='block',
        ),
        migrations.RemoveField(
            model_name='building',
            name='streetName',
        ),
        migrations.RemoveField(
            model_name='building',
            name='streetNumber',
        ),
        migrations.AddField(
            model_name='building',
            name='streetAddress',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
