# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldgquery', '0007_auto_20170421_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='groundElevation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='dateBuilt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='building',
            name='roofHeight',
            field=models.FloatField(),
        ),
    ]
