# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldgquery', '0008_auto_20170422_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='centerLat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='building',
            name='centerLon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='building',
            name='numFloors',
            field=models.FloatField(),
        ),
    ]
