# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bldgquery', '0010_auto_20170422_0343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False},
        ),
    ]
