# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bldgquery', '0011_auto_20170422_0420'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='building',
            table='bldgquery_building',
        ),
    ]
