# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldgquery', '0013_auto_20170422_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='BBL',
        ),
        migrations.RemoveField(
            model_name='building',
            name='BIN',
        ),
        migrations.RemoveField(
            model_name='building',
            name='centerLat',
        ),
        migrations.RemoveField(
            model_name='building',
            name='centerLon',
        ),
        migrations.RemoveField(
            model_name='building',
            name='dateBuilt',
        ),
        migrations.RemoveField(
            model_name='building',
            name='groundElevation',
        ),
        migrations.RemoveField(
            model_name='building',
            name='numFloors',
        ),
        migrations.RemoveField(
            model_name='building',
            name='roofHeight',
        ),
        migrations.RemoveField(
            model_name='building',
            name='streetAddress',
        ),
        migrations.AddField(
            model_name='building',
            name='bbl',
            field=models.IntegerField(db_column='BBL', default=9999999),
        ),
        migrations.AddField(
            model_name='building',
            name='bin',
            field=models.IntegerField(db_column='BIN', default=9999999),
        ),
        migrations.AddField(
            model_name='building',
            name='centerlat',
            field=models.FloatField(db_column='centerLat', default=0.0),
        ),
        migrations.AddField(
            model_name='building',
            name='centerlon',
            field=models.FloatField(db_column='centerLon', default=0.0),
        ),
        migrations.AddField(
            model_name='building',
            name='datebuilt',
            field=models.IntegerField(db_column='dateBuilt', default=999, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='groundelevation',
            field=models.FloatField(db_column='groundElevation', default=9, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='numfloors',
            field=models.FloatField(db_column='numFloors', default=37, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='roofheight',
            field=models.FloatField(db_column='roofHeight', default=9999, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='streetaddress',
            field=models.CharField(db_column='streetAddress', default='123 Steet Ave', max_length=150),
        ),
    ]
