# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldgquery', '0014_auto_20170422_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='bbl',
            field=models.IntegerField(db_column='BBL'),
        ),
        migrations.AlterField(
            model_name='building',
            name='bin',
            field=models.IntegerField(db_column='BIN'),
        ),
        migrations.AlterField(
            model_name='building',
            name='centerlat',
            field=models.FloatField(db_column='centerLat'),
        ),
        migrations.AlterField(
            model_name='building',
            name='centerlon',
            field=models.FloatField(db_column='centerLon'),
        ),
        migrations.AlterField(
            model_name='building',
            name='datebuilt',
            field=models.IntegerField(db_column='dateBuilt', null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='groundelevation',
            field=models.FloatField(db_column='groundElevation', null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='numfloors',
            field=models.FloatField(db_column='numFloors', null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='roofheight',
            field=models.FloatField(db_column='roofHeight', null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='streetaddress',
            field=models.CharField(db_column='streetAddress', max_length=150),
        ),
    ]
