# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldgquery', '0015_auto_20170422_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullBuilding',
            fields=[
                ('bldg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bbl', models.IntegerField()),
                ('bin', models.IntegerField()),
                ('datebuilt', models.IntegerField()),
                ('roofheight', models.FloatField()),
                ('groundelevation', models.FloatField()),
                ('numfloors', models.FloatField()),
                ('centerlat', models.FloatField()),
                ('centerlon', models.FloatField()),
                ('streetaddress', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='bbl',
        ),
        migrations.RemoveField(
            model_name='building',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='building',
            name='centerlat',
        ),
        migrations.RemoveField(
            model_name='building',
            name='centerlon',
        ),
        migrations.RemoveField(
            model_name='building',
            name='datebuilt',
        ),
        migrations.RemoveField(
            model_name='building',
            name='groundelevation',
        ),
        migrations.RemoveField(
            model_name='building',
            name='numfloors',
        ),
        migrations.RemoveField(
            model_name='building',
            name='roofheight',
        ),
        migrations.RemoveField(
            model_name='building',
            name='streetaddress',
        ),
        migrations.AddField(
            model_name='building',
            name='BBL',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='BIN',
            field=models.IntegerField(default=9999999),
        ),
        migrations.AddField(
            model_name='building',
            name='centerLat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='centerLon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='dateBuilt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='groundElevation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='numFloors',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='roofHeight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='streetAddress',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterModelTable(
            name='building',
            table=None,
        ),
    ]
